### ISSUE TITLE
Malformed JSON issue

### ISSUE THREAD

**Issue by msshw** [honojs/middleware#81]
Hello there! 

I recently began experimenting with `@hono/zod-validator`. Unfortunately, I encountered an error message stating `Malformed JSON in request body` in request body. I was wondering if anyone has come across this issue before and if there's anyone who could offer assistance in finding a solution. 

My client sends a request:
``` javascript
import type { AppType } from '../server/router'
import { hc } from 'hono/client'

const client = hc<AppType>('https://localhost/');

const res = await client.testrpc.$post({
  json: {
    x: 'Hello',
  },
});
```

And the server receives it:
``` javascript
const route = app.post(
  '/testrpc',
  zValidator(
    'json',
    z.object({
      x: z.string(),
    })
  ),
  (c) => {
    const data = c.req.valid('json');
    return c.jsonT({
      success: true,
      message: `${data.x}`,
    }, 200);
  }
)
```

Thank you in advance for your help!

**Comment by yusukebe** [comment]
Hi @msshw !

I tried your code on Cloudflare Workers with Wrangler, but it works well.
So, I would like to know which platform/time you use.

**Comment by msshw** [comment]
Hi @yusukebe! I use bun js.

**Comment by Jarred-Sumner** [comment]
@msshw are you on Bun v0.5.9?

**Comment by msshw** [comment]
@Jarred-Sumner I am on 0.5.8

**Comment by Jarred-Sumner** [comment]
Can you try on Bun v0.5.9 (`bun upgrade`)? I can’t guarantee it is fixed but we did fix a possibly related bug in the most recent release

**Comment by msshw** [comment]
Unfortunately, I get the same result with bun@0.5.9

**Comment by yusukebe** [comment]
Hi @Jarred-Sumner @msshw !

I have tried running that on Bun. Then I got the `Malformed JSON in request body` error, the same as @msshw. The result is the same in v0.5.9 and v0.5.8.

**Comment by Jarred-Sumner** [comment]
Can you give this another try on the canary build? We pushed a fix that might’ve fixed this yesterday

**Comment by yusukebe** [comment]
@Jarred-Sumner

Thanks for letting us know but It is still not working. I can find the minimal code to reproduce that issue:

```ts
export default {
  fetch: async (req: Request) => {
    const clone = req.clone()
    const data = await clone.json()
    return new Response(JSON.stringify(data))
  },
}
```

Then post the request:

```
curl -X POST -d '{"foo": "bar"}' http://localhost:3000/
```

<img width="371" alt="SS" src="https://user-images.githubusercontent.com/10682/232176134-d67bcd7b-e2e1-435d-97a4-e2b16d378ded.png">


It is necessary to `clone()` because it may decode a JSON object more than once. Without `clone`, the second `json()` will fail because `Body` is used. At least in Cloudflare Workers, we can do `json()` with the cloned `Request`, we need to be able to do that in Bun.

**Comment by Jarred-Sumner** [comment]
Oh, the bug is with .clone(). That makes sense now. We haven't implemented clone for this usecase yet. 

A temporary but not good workaround would be to do await req.blob() and bun has a non-standard .json() function on the Blob prototype (to make it more aligned with Request and Response)

**Comment by yusukebe** [comment]
@Jarred-Sumner 

The content with `clone.blob()` will be blank. Does it mean that it is not implemented yet?

```ts
const clone = req.clone()
const blob = await clone.blob()
console.log(blob.size) // 0
```

**Comment by Jarred-Sumner** [comment]
Will be fixed in Bun v0.7.2 https://github.com/oven-sh/bun/issues/1381

**Comment by yusukebe** [comment]
@Jarred-Sumner Thanks!

**Comment by yusukebe** [comment]
Hi @Jarred-Sumner 

I've upgraded Bun to v0.7.2, but it's not be fixed. Could you check it?

**Comment by Lucasnribeiro** [comment]
0.7.3 still has this bug

**Comment by twinstae** [comment]
bun v0.8.1 still...

**Comment by juhojo** [comment]
I noticed that this error occurs if a HTTP request is missing `Content-Type: "application/json"` header. Maybe helpful, probably not 🤷.

**Comment by chronark** [comment]
Also ran into this, setting the content type to json fixed it

**Comment by ganevdev** [comment]
Maybe this will help someone. `Malformed JSON in request body` error can occur if you use the GET method. Use the POST method (because we are sending data in the body). `Malformed JSON in request body` error is not very informative about this.

**Comment by juliomuhlbauer** [comment]
> Maybe this will help someone. `Malformed JSON in request body` error can occur if you use the GET method. Use the POST method (because we are sending data in the body). `Malformed JSON in request body` error is not very informative about this.

So, I can't send a body to a get request?

**Comment by spiffytech** [comment]
> So, I can't send a body to a get request?

Setting aside what Hono supports, [it is inadvisable](https://www.baeldung.com/cs/http-get-with-body) to include a body with `GET`: many systems aren't designed to handle it, as the original spec was ambiguous as to whether it was acceptable.

In the future, the solution will be the HTTP `QUERY` method, which is [on the standards track](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html). It functions like `GET` + body, except all systems will support it correctly since it was designed for this purpose from the beginning.

**Comment by juliomuhlbauer** [comment]
N

> > So, I can't send a body to a get request?
> 
> Setting aside what Hono supports, [it is inadvisable](https://www.baeldung.com/cs/http-get-with-body) to include a body with `GET`: many systems aren't designed to handle it, as the original spec was ambiguous as to whether it was acceptable.
> 
> In the future, the solution will be the HTTP `QUERY` method, which is [on the standards track](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html). It functions like `GET` + body, except all systems will support it correctly since it was designed for this purpose from the beginning.

Thanks!
And what would be the recommended approach as of now with Hono?

**Comment by rohit-iwnl** [comment]
> Maybe this will help someone. `Malformed JSON in request body` error can occur if you use the GET method. Use the POST method (because we are sending data in the body). `Malformed JSON in request body` error is not very informative about this.

Saved me debug hours. Thanks 👍

**Comment by BakauDesign** [comment]
BRUHH

**Comment by BakauDesign** [comment]
is Hono ready for production? Is this question worth asking? 🤣🤣😂😂

**Comment by cueedee** [comment]
With the advent of [`bun@1.3.6`](https://bun.com/blog/bun-v1.3.6#response-json-object-is-now-3-5x-faster) it seems that this ghost has re-appeared.

Inspecting the exception causing the _"Malformed JSON in request body"_ error to be thrown at https://github.com/honojs/hono/blob/v4.11.5/src/validator/validator.ts#L101, I find that it originates from https://github.com/honojs/hono/blob/v4.11.5/src/request.ts#L236 causing a **"TypeError: undefined is not a function"** error.
I suspected the `raw[key]()`there to be the culprit, but inspecting it (via a strategically placed `console.log(raw[key])`) revealed nothing more extaordinary than 
```
function text() {
    [native code]
}
```

What makes this an elusive bugger is that it only occurs after handling a great number (`> 4.5K`-ish) of requests without a hitch. The exact request does not appear to matter, but once it _does_ happen, it will keep happening until a restart.

**Comment by yusukebe** [comment]
@cueedee Was it solved?

**Comment by cueedee** [comment]
> [@cueedee](https://github.com/cueedee) Was it solved?

@yusukebe, according to the [`bun@1.3.7` changelog](https://bun.com/blog/bun-v1.3.7#fetch-api), yes!

> * Fixed: `Request.prototype.text()` incorrectly throwing "TypeError: undefined is not a function" in certain cases under load

**Comment by yusukebe** [comment]
I think this problem has been fixed on the Bun side. So, closing this issue. If you have any issues, please open a new issue. Thanks.
